### ISSUE TITLE
Set up readme.md

### ISSUE THREAD

**Issue by asunwoo98** [nyu-software-engineering/ar-mini-games#12]
From https://github.com/nyu-software-engineering/ar-mini-games/issues/10

**Comment by koktavy** [comment]
README does not link to REQUIREMENTS.md. We should also add a nice description of ourselves as the team behind this project.

Again, Quip has a [nice example](https://github.com/nyu-software-engineering/quip-thinking) of this, linking their bios to their respective GitHub accounts.
