### ISSUE TITLE
As a developer I want to automatically detect the user's platform to streamline development

### ISSUE THREAD

**Issue by koktavy** [nyu-software-engineering/ar-mini-games#126]
As a developer I want to automatically detect the user's platform to streamline development

## Estimate of work
* M

## Acceptance criteria
- [x] #127 Detect platform on initialization, switch camera settings for ARKit/ARCore
- [x] Must pass automated tests
- [x] Must be code reviewed, and checked for functionality by the team
- [x] Must be checked into the master branch via pull request

**Comment by satyajeetmaharana** [comment]
Hi Guys, I see that there are multiple labels for this issue. Issues in the Task Board must be labeled either "user story", "spike", or "task", but never more than one of those labels.
