### ISSUE TITLE
Must be checked into the master branch via pull request

### ISSUE THREAD

**Issue by asunwoo98** [nyu-software-engineering/ar-mini-games#26]
https://github.com/nyu-software-engineering/ar-mini-games/issues/2

**Comment by charleswdickstein** [comment]
I'm not sure what this task is referring to? Are you saying the general practice is to pull then push or is there something specific that needs to merged into master?

**Comment by koktavy** [comment]
Hmm this does become confusing as its own task. The command `git fetch --all` should be used to download remote changes from the repo, but will not try to merge them right away like `git pull`.

In reference to #2 this would be a demo Unity scene created within a separate branch, which should be submitted to the master branch as a pull request. Any code we add to this project should originate from a separate dev branch, ideally tackling one straightforward goal in the form of a task. These dev branches will then be pull requested, peer-reviewed, and merged into the project once agreed upon.

(At which point any in-progress branches will need to have master merged _into them_ to pick up the latest changes. If that is confusing, we'll go over it again when we get there.)

**Comment by koktavy** [comment]
This is described as an integral part of our [contributing process](https://github.com/nyu-software-engineering/ar-mini-games/blob/master/CONTRIBUTING.md) and should not be an issue of its own. We can go over the process in depth together on Saturday.
