### ISSUE TITLE
ARCore Cloud Anchors 

### ISSUE THREAD

**Issue by charleswdickstein** [nyu-software-engineering/ar-mini-games#28]
* [ ] Download ARCore Cloud Anchors 
* [ ] Get sample app working on iOS and Android across all dev devices

**Comment by koktavy** [comment]
I'm reconstructing this issue and #27 into tasks of "Learn ARCore" spikes for each of us. Additionally staging it for Sprint 1 (may not be necessary until sprint 2) after our timeline discussion today.
